# Generated by Django 5.2.13 on 2026-05-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drinks',
            options={'ordering': ['sort'], 'verbose_name': 'Крепкие напитки', 'verbose_name_plural': 'Крепкие напитки'},
        ),
        migrations.AlterField(
            model_name='drinks',
            name='sort',
            field=models.IntegerField(blank=True, help_text='Число для сортировки отображения напитков', null=True, verbose_name='Для очередности отображения'),
        ),
    ]